#!/bin/bash

if [ "$1" == "run" ]; then
    node ${GIGAHTML}/js/run-package-script.js $(pwd) $2

elif [[ "$1" == "build" || "$1" == "delete-build"  ]]; then
    node ${GIGAHTML}/js/run-package-script.js $(pwd) $1

elif [ "$1" == "init" ]; then
    ${GIGAHTML}/shell/init

fi

> ${GIGAHTML}/js/runtime-values.js
